os:
  - linux

language: perl
perl:
  - "5.10"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install libgdal-dev
#  - cpanm --notest Alien::Build
#  - cpanm --notest ExtUtils::MakeMaker
#  - cpanm --notest HTTP::Tiny
#  - cpanm --notest PkgConfig
#  - cpanm --notest Sort::Versions
#  - svn co https://github.com/shawnlaffan/perl-alien-gdal.git/trunk alien-gdal; cd alien-gdal; perl Makefile.PL; make install; cd ..; rm -rf alien-gdal
#  - cpanm https://github.com/shawnlaffan/perl-alien-gdal.git

install:
  - cpanm --installdeps --notest .

script: "perl Makefile.PL; make test"

branches:
  only:
    - master

notifications:
  recipients:
    - ari.jolma@gmail.com
  email:
    on_success: change
    on_failure: always
